/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman.GUI;

import hangman.Engine.GameLogic;
import hangman.Engine.GameLogic.GameDifficulty;
import hangman.Engine.GameLogic.GameType;
import hangman.Engine.Player;
import hangman.GUI.GameAreaPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.AbstractButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author P
 */
public class GamePreAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form GamePreAreaPanel
     */
    public GamePreAreaPanel() {
        initComponents();
        setBackground(Color.WHITE);
        
         GameLogic.setDifficulty(GameDifficulty.MEDIUM);
    
         // Na podstawie nazw kategorii w bazie pododować tutaj, a następnie
         // przekazać do GameLogic rodzaj kategorii (po ID?)
         categoryCombo.addItem(makeObj("Rzeczy"));
          categoryCombo.addItem(makeObj("Kuchnia"));
           categoryCombo.addItem(makeObj("Zwierzęta"));
           
           player2Label.setVisible(false);
           playerName2.setVisible(false);
           
           typeSingleRadio.addItemListener(new VoteItemListener());
           typeMultipleRadio.addItemListener(new VoteItemListener());
           typePvpRadio.addItemListener(new VoteItemListener());
           
           GameLogic.setType(GameType.SINGLE); 
    }
    
    class VoteItemListener implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent e) {
            boolean selected = (e.getStateChange() == ItemEvent.SELECTED);
            AbstractButton button = (AbstractButton)e.getItemSelectable();
            if(selected && (button.getActionCommand() == null ? 
                    typePvpRadio.getActionCommand() == null : button.getActionCommand().equals(typePvpRadio.getActionCommand()))){
                player1Label.setText("Write 1st player name:");
                player2Label.setVisible(true);
                playerName2.setVisible(true);
            }
            else{
                player1Label.setText("Write your name:");
                player2Label.setVisible(false);
                playerName2.setVisible(false);
            }
            
            switch(button.getActionCommand()){
                case "Single game":
                {
                    GameLogic.setType(GameType.SINGLE); break;
                }
                 case "Multiple levels":
                {
                    GameLogic.setType(GameType.MULTI); break;
                }
                  case "Player VS Player":
                {
                    GameLogic.setType(GameType.PVP); break;
                }
            }
           
        }
        
    }
   
    private Object makeObj(final String item)  {
        return new Object() { public String toString() { return item; } };
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameTypeButGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        statusBarText = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        levelSlider = new javax.swing.JSlider();
        levelLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeSingleRadio = new javax.swing.JRadioButton();
        typePvpRadio = new javax.swing.JRadioButton();
        typeMultipleRadio = new javax.swing.JRadioButton();
        categoryLabel = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox();
        graphicPanel = new javax.swing.JPanel();
        graphicIcLabel = new javax.swing.JLabel();
        player1Label = new javax.swing.JLabel();
        player2Label = new javax.swing.JLabel();
        playerName1 = new javax.swing.JTextField();
        playerName2 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        statusBarText.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        statusBarText.setForeground(new java.awt.Color(255, 255, 255));
        statusBarText.setText("Choose a category.");
        statusBarText.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusBarText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusBarText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        playButton.setBackground(new java.awt.Color(51, 51, 51));
        playButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playButton.setForeground(new java.awt.Color(255, 255, 255));
        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        levelSlider.setMaximum(2);
        levelSlider.setToolTipText("");
        levelSlider.setValue(1);
        levelSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                levelSliderStateChanged(evt);
            }
        });

        levelLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        levelLabel.setText("Choose your difficulty level (chosen: medium).");

        typeLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        typeLabel.setText("Choose game type.");

        gameTypeButGroup.add(typeSingleRadio);
        typeSingleRadio.setSelected(true);
        typeSingleRadio.setText("Single game");
        typeSingleRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                typeSingleRadioMouseEntered(evt);
            }
        });

        gameTypeButGroup.add(typePvpRadio);
        typePvpRadio.setText("Player VS Player");
        typePvpRadio.setToolTipText("");

        gameTypeButGroup.add(typeMultipleRadio);
        typeMultipleRadio.setText("Multiple levels");
        typeMultipleRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                typeMultipleRadioMouseEntered(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        categoryLabel.setText("Choose word category.");

        graphicIcLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/BCKG.jpg"))); // NOI18N
        graphicIcLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout graphicPanelLayout = new javax.swing.GroupLayout(graphicPanel);
        graphicPanel.setLayout(graphicPanelLayout);
        graphicPanelLayout.setHorizontalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicPanelLayout.createSequentialGroup()
                .addComponent(graphicIcLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        graphicPanelLayout.setVerticalGroup(
            graphicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphicIcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        player1Label.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        player1Label.setText("Write your name:");

        player2Label.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        player2Label.setText("Write 2nd player name:");

        playerName1.setText("Hang On!");

        playerName2.setText("Hang On!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(levelLabel)
                            .addComponent(typeLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addComponent(levelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoryLabel)
                                    .addComponent(player1Label)
                                    .addComponent(player2Label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(categoryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(typePvpRadio)
                                            .addComponent(typeMultipleRadio)
                                            .addComponent(typeSingleRadio)
                                            .addComponent(playerName1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                                    .addComponent(playerName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(graphicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(levelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(levelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeSingleRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeMultipleRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typePvpRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(player2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                 GameLogic.players[0] = new Player(playerName1.getText());
                 if(GameLogic.gType == GameType.PVP){
                   GameLogic.players[1] = new Player(playerName2.getText());
                 }
                 
                  GameAreaPanel GAP  = new GameAreaPanel();
                JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(GamePreAreaPanel.this);
                topFrame.getContentPane().removeAll();
                topFrame.add(GAP);
                topFrame.validate();
                topFrame.repaint();

            }
        });
    }//GEN-LAST:event_playButtonActionPerformed

    private String changeLevel(int value){
         switch(value){
            case 0:
            {
                GameLogic.setDifficulty(GameDifficulty.EASY);
                return "easy";
            }
            case 1:
            {
                GameLogic.setDifficulty(GameDifficulty.MEDIUM);
                return "medium";
            }
            case 2:
            {
                GameLogic.setDifficulty(GameDifficulty.HARD);
                return "hard";
            }
            default:
            {
                GameLogic.setDifficulty(GameDifficulty.MEDIUM);
                return "medium";
            }
        }
    }
    
    private void levelSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_levelSliderStateChanged
        levelLabel.setText("Choose your difficulty level (chosen: "+changeLevel(levelSlider.getValue())+").");
    }//GEN-LAST:event_levelSliderStateChanged

    private void typeSingleRadioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeSingleRadioMouseEntered
        statusBarText.setText("A single game - only one Hangman to solve.");
    }//GEN-LAST:event_typeSingleRadioMouseEntered

    private void typeMultipleRadioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeMultipleRadioMouseEntered
        statusBarText.setText("A multiple level game - you have to solve multiple Hangmans to win.");
    }//GEN-LAST:event_typeMultipleRadioMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoryCombo;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.ButtonGroup gameTypeButGroup;
    private javax.swing.JLabel graphicIcLabel;
    private javax.swing.JPanel graphicPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JSlider levelSlider;
    private javax.swing.JButton playButton;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player2Label;
    private javax.swing.JTextField playerName1;
    private javax.swing.JTextField playerName2;
    private javax.swing.JLabel statusBarText;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JRadioButton typeMultipleRadio;
    private javax.swing.JRadioButton typePvpRadio;
    private javax.swing.JRadioButton typeSingleRadio;
    // End of variables declaration//GEN-END:variables
}
